SRS documentation
NSU-Team-Project-Dormitory/Effective_Communication_with_Dormitory_Settlement pull request #6
Opened 2023-11-30 18:15 UTC by MelloTheCatLover

Making final version of SRS.

2023-12-04 04:34 UTC, vlasival requested changes

2023-12-04 04:34 UTC, vlasival commented on SRS v2.md
> +At the moment, there is no unified system for communication between departments responsible for settling students in dormitories, all work has to be done manually. There is a need to create and imple
There is a need to create... - возможно, сложное для понимания предложение.
Я бы сделал It is necessary to create and implement a system for tracking student residence.

2023-12-04 04:34 UTC, vlasival commented on SRS v2.md
> +### Основной сценарий
Нужен англичанин, который переведёт всё это на англиски

2023-12-04 04:34 UTC, vlasival commented on SRS v2.md
> +Основным сценарией будем считать работу сотрудника с программой с момента подачи студентом заявления на комнату в общежитие до момента окончания обучения студента в университете.
По сути не до окончания обучения в университете, а до окончания проживания в общежитиях и  взаимодействия с общажной системой

2023-12-04 04:34 UTC, vlasival commented on SRS v2.md
> +1. Необходимо изменить данные карточки студента.
Необходимо изменить данные о студенте.

2023-12-04 04:34 UTC, vlasival commented on SRS v2.md
> +1. Студентов необходимо поменять местами.
Можно проще: студента необходимо переселить в другую комнату (vice-versa)

2023-12-04 04:34 UTC, vlasival commented on SRS v2.md
> +1. Необходимо изменить данные карточки студента.
Необходимо добавить информацию о студенте.

2023-12-04 04:47 UTC, MelloTheCatLover commented on SRS v2.md
> +1. Необходимо изменить данные карточки студента.
Окей

2023-12-05 12:20 UTC, NotWhaleee commented on SRS v2.md
> +At the moment, there is no unified system for communication between departments responsible for settling students in dormitories, all work has to be done manually. There is a need to create and imple
да вроде норм

2023-12-05 12:21 UTC, NotWhaleee commented on SRS v2.md
> +1. Необходимо изменить данные карточки студента.
я бы перефразировал "Студентов необходимо поменять местами.", не очень очевидно, о чем идет речь

2023-12-05 12:24 UTC, NotWhaleee commented on SRS v2.md
> +- Замена студентов местами
- "Замена студентов местами", такая формулировка тоже не оч по мне

2024-02-15 12:28 UTC, merged